Health auth screens
bipolarbridges/companion-app pull request #29
Opened 2021-03-05 18:50 UTC by crugwiro

## Changes
- Implements screens that allow a mobile user to control health data permissions.
- Prompts users to enable the authorization

## Requirements
N/A

## PR Dependencies
N/A

## Merged Branches and Other Dependencies
Merged branch(es):
Other dependencies:

## Subtasks / Progress
TODO

## Preview
TODO

## Testing
Manual 
For testing:
- Make sure DOB is set in Apple healthKit

2021-04-08 17:15 UTC, wynnset commented
Hi @crugwiro you had mentioned this would be ready by Wednesday so I just wanted to follow up. Thank you

2021-04-08 17:59 UTC, crugwiro commented
@wynnset should be ready by end of day today.

2021-04-08 21:39 UTC, crugwiro commented
@wynnset This is now ready for review, assigning it to @cara-wong

2021-04-15 05:16 UTC, cara-wong requested changes
Tested this PR on a real ios device, an ios sim and an android sim. Found some user flow issues - working with Clement to point out the issues.

2021-04-30 07:47 UTC, cara-wong requested changes
This is looking really good!
I left some comments on certain lines. Some of the comments are regarding what seems like old logic that is just commented out, so I'm checking if we can remove these. Some comments are also just questions, so feel free to resolve if it's a non-issue. In addition:
1. On the Health Data page in settings, in the design the text reading "We are collecting your health data to build..." is on this page whether the permissions are enabled or disabled. Right now there's only text when it's disabled.
2. On a real ios device, the settings link takes you to the wrong place in settings. I know you mentioned this last meeting, so just documenting it so it can be fixed before this PR is merged.
3. On my iphone 8+, when permissions are disabled and there's a prompt on the home screen, the past check-ins are slightly cut off. (suggests we should be testing this on multiple screen sizes to ensure dynamic UI)
4. Probably good to have someone else test this on a real android device

2021-04-30 07:47 UTC, cara-wong commented on mobile/src/controllers/Notifications.ts
> +//
Unneeded cosmetic changes in this file (start of comment, removed line)

2021-04-30 07:47 UTC, cara-wong commented on mobile/src/controllers/User.ts
> +            // await this.notifications.initAsync();
is this comment needed?

2021-04-30 07:47 UTC, cara-wong commented on mobile/src/controllers/index.ts
> +            // await this.User.notifications.initAsync();
is this comment needed?

2021-04-30 07:47 UTC, cara-wong commented on mobile/src/helpers/health.ts
> +  return await GoogleFit.checkIsAuthorized().then (() => {
are the comments in this method needed? They look like old logic that is no longer being used

2021-04-30 07:47 UTC, cara-wong commented on mobile/src/stateMachine/scenario.ts
> +            // { target: States.HomeRouter, trigger: Triggers.Submit },
comment needed?

2021-04-30 07:47 UTC, cara-wong commented on mobile/src/stateMachine/scenario.ts
> +            // { target: States.ConfirmAccount, trigger: Triggers.Secondary },
comment needed?

2021-04-30 07:47 UTC, cara-wong commented on mobile/src/stateMachine/views/healthData/healthScopes.tsx
> +        // this._contentHeight = this.persona.setupContainerHeight(minContentHeight, { rotation: 405 });
comment needed?

2021-04-30 07:47 UTC, cara-wong commented on mobile/src/stateMachine/views/healthData/healthScopes.tsx
> +        // opacity: new Animated.Value(0),
comment needed?

2021-04-30 07:47 UTC, cara-wong commented on mobile/src/stateMachine/views/login/notificationsPermission.ts
> +import GoogleFit, { Scopes } from 'react-native-google-fit';
unused import statement - is this needed?

2021-04-30 07:47 UTC, cara-wong commented on mobile/src/stateMachine/views/main/home.tsx
> +                    {/* <ScrollView> */}
comments in the return statement needed?

2021-04-30 07:47 UTC, cara-wong commented on mobile/src/stateMachine/views/main/home.tsx
> +        // height: 100,
comment needed?

2021-04-30 07:47 UTC, cara-wong commented on mobile/src/stateMachine/views/healthData/permInstructions.tsx
> +export const logger = createLogger('[endQOL]');
logger shouldn't preceed logs with "endQol" for this view

2021-04-30 07:47 UTC, cara-wong commented on mobile/src/stateMachine/views/healthData/permInstructions.tsx
> +{title : 'Next, open your personal health settings by tapping the top right corner in the App ', image: Images.screen2},
App here shouldn't be capitalized

2021-04-30 07:47 UTC, cara-wong commented on mobile/src/viewModels/HealthPermissionsViewModel.ts
> +{title:"BMI", icon:Images.keyIcon, description: "Allow Companion kit to access BMI info"}];
should we be showing BMI if we don't ask for it?

2021-06-03 19:59 UTC, rlnsy commented
@SukiCai just a reminder to take care of this PR when you have a chance (make sure the comments are resolved, make sure it is fully merged into your branch, and close when done)

2021-06-03 20:29 UTC, SukiCai commented
Hi @rlnsy, I've resolved all the comment above and fully merged into PR #52 , we can close this PR now

2021-06-15 05:46 UTC, closed without merging